### PR TITLE
[docs] Add controller flow docs

### PR DESCRIPTION
**Pull request by gyfora**
## What is the purpose of the change

Add detailed documentation for the core operator controller flow

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency):no
  - The public API, i.e., is any changes to the `CustomResourceDescriptors`: no
  - Core observer or reconciler logic that is regularly executed:no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? docs

### CODE REVIEW

**Review by morhidi — APPROVED** [review]
+1 I was unable to render the pictures on this PR.

**Comment by gyfora** [comment]
> +1 I was unable to render the pictures on this PR.

Sorry @morhidi , I should have posted some screenshots. Unfortunately I don’t have the laptop on me

**Comment by morhidi** [comment]
> > +1 I was unable to render the pictures on this PR.
> 
> Sorry @morhidi , I should have posted some screenshots. Unfortunately I don’t have the laptop on me
hm.. it is supposed to work without screenshots. I checked and the svgs are not formatted properly. The `<?xml version="1.0" encoding="UTF-8"?>` tag is duplicated in them.

**Comment by gyfora** [comment]
I will remove them once back from holiday , this is not urgent. Thank you!

**Pull request merged**
