### PR TITLE
[FLINK-26405] Improve the check of HA mode

### PR DESCRIPTION
**Pull request by bgeng777**
- Use `HighAvailabilityMode.isHighAvailabilityModeActivated()` to improve the check process of HA mode
- This PR is a followup of #29

### CODE REVIEW

**Comment by bgeng777** [comment]
Sorry for bothering you guys again  @wangyang0918 @gyfora .

**Review by gyfora — APPROVED** [review]
Looks good to me but I have kind of lost my self-confidence 😄

**Review by wangyang0918 — APPROVED** [review]
+1 for merging.

**Comment by wangyang0918** [comment]
> Looks good to me but I have kind of lost my self-confidence 😄

Hmm... My bad.

**Pull request merged**
