### PR TITLE
DO_NOT_MERGE [FLINK-30151] Remove AuditUtils from operator error

### PR DESCRIPTION
**Pull request by gaborgsomogyi**
## What is the purpose of the change

Just testing.

## Brief change log

TODO

## Verifying this change

Existing e2e tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changes to the `CustomResourceDescriptors`: no
  - Core observer or reconciler logic that is regularly executed: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by mbalassi** [comment]
@gaborgsomogyi is this still relevant or can we close this?

**Comment by gaborgsomogyi** [comment]
At some point I need to come back and execute all tests to find out the reason. Now we've added several bugfixes so I need to rebase.

**Comment by gaborgsomogyi** [comment]
Failed on docker build, interesting...

**Comment by gaborgsomogyi** [comment]
Now not having time to push this so closing temporarily.

**Pull request closed without merging**
