### PR TITLE
[FLINK-33357] add Apache Software License 2

### PR DESCRIPTION
**Pull request by caicancai**
## What is the purpose of the change

Flinkdeployments.flink.apache.org - v1.yml and flinksessionjobs.flink.apache.org - v1. yml don't add add Apache Software License 2

Ref - FLINK-33357

## Brief change log

TRIVIAL AS IS.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changes to the `CustomResourceDescriptors`: (yes / no)
  - Core observer or reconciler logic that is regularly executed: (yes / no)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
Thank you!

Maybe we can add an autotool like [hawkeye](https://github.com/korandoru/hawkeye) to automize this kind of lag.

**Comment by caicancai** [comment]
I am working on this cli issue

**Comment by tisonkun** [comment]
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Flink Kubernetes: 1.7-SNAPSHOT:
[INFO] 
[INFO] Flink Kubernetes: .................................. SUCCESS [  5.258 s]
[INFO] Flink Kubernetes Standalone ........................ SUCCESS [ 23.994 s]
[INFO] Flink Kubernetes Operator Api ...................... SUCCESS [ 35.975 s]
[INFO] Flink Autoscaler ................................... SUCCESS [ 19.100 s]
[INFO] Flink Kubernetes Operator .......................... SUCCESS [06:56 min]
[INFO] Flink Kubernetes Webhook ........................... SUCCESS [ 16.950 s]
[INFO] Flink Kubernetes Docs .............................. SUCCESS [ 14.774 s]
[INFO] Flink SQL Runner Example ........................... SUCCESS [  7.986 s]
[INFO] Flink Beam Example ................................. SUCCESS [ 43.310 s]
[INFO] Flink Kubernetes Client Code Example ............... SUCCESS [ 10.857 s]
[INFO] Flink Autoscaler Test Job .......................... SUCCESS [  8.115 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10:03 min
[INFO] Finished at: 2023-10-25T06:11:12Z
[INFO] ------------------------------------------------------------------------
Please generate the java doc via 'mvn clean install -DskipTests -Pgenerate-docs' again
Error: Process completed with exit code 1.
```

succeed but fail - why?

cc @gyfora

**Comment by caicancai** [comment]
捕获
Perform mvn clean install -DskipTests -Pgenerate-docs
There are also some changes to the file, which I don't know if I need to upload

**Comment by gyfora** [comment]
These are generated files based on source code that is Apache licensed .

I think we don’t need the header.

@mbalassi what do you think ?

**Comment by swap-10** [comment]
> Perform mvn clean install -DskipTests -Pgenerate-docs. After that, the license I added disappeared. Why？ I'll resubmit the initial version cc @tisonkun @gyfora

It's auto-generated by Fabric8, "manual edits may get overriddedn"

**Comment by gyfora** [comment]
Actually we attach the header during release already : https://github.com/apache/flink-kubernetes-operator/blob/main/tools/releasing/create_source_release.sh#L98

**Comment by swap-10** [comment]
Can the script used to attach that in release be made a part of the generate-docs here itself?

**Comment by tisonkun** [comment]
Yep. If it's generated, then it won't be an issue.

**Comment by caicancai** [comment]
Thank you for your replies and answers

**Pull request closed without merging**
