### PR TITLE
[hotfix] Clean up warnings and unnecessary code in tests

### PR DESCRIPTION
**Pull request by gyfora**
## What is the purpose of the change

Clean up warnings and some unnecessary, duplicated in the operator tests. 

 - Fix missing generic parameters
 - Remove unused methods/params
 - Code style cleanup
 - Remove some code duplications
 - Replace deprecated junit.assert use

## Verifying this change

This change is already covered by existing tests

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changes to the `CustomResourceDescriptors`: no
  - Core observer or reconciler logic that is regularly executed: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by gyfora** [comment]
@Aitozi @morhidi

**Review by Aitozi — APPROVED** [review]
Nice clean up, LGTM +1

**Comment by morhidi** [comment]
yeah +1 :) Do you think guys we could/should enable some warning elimination mechanism also on the project or it's too ambitious?

**Comment by Aitozi** [comment]
@morhidi I think we have already use the same checkstyle from the flink project. But there are still some are not enforced eg: the deprecated junit.assert use, because the flink project have not replace all of them in the project. As for the flink-kubernetes-operator do not have too much history code, I'm happy to see some more rule to guard the behavior :)

**Comment by gyfora** [comment]
I will take a look into some extra rules

**Pull request merged**
