### PR TITLE
[FLINK-26706][hotfix] Introduce Ingress URL templating

### PR DESCRIPTION
**Pull request by morhidi**
- fixed NPE in `FlinkConfigBuilderTest`

### CODE REVIEW

**Comment by morhidi** [comment]
cc @wangyang0918

**Comment by wangyang0918** [comment]
Could you work under FLINK-26815 and have a look why the CI does not fail?

**Comment by gyfora** [comment]
> Could you work under [FLINK-26815](https://issues.apache.org/jira/browse/FLINK-26815) and have a look why the CI does not fail?

that would be nice to fix, I agree

**Comment by morhidi** [comment]
fixed in https://github.com/apache/flink-kubernetes-operator/pull/102

**Pull request closed without merging**
