### PR TITLE
[hotfix] Prevent release branches from deleted and force pushes

### PR DESCRIPTION
**Pull request by tisonkun**
See also https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-Branchprotection

### CODE REVIEW

**Comment by gyfora** [comment]
Should we add something about this to the release process?

**Comment by tisonkun** [comment]
Hi @gyfora!

Make sense. I ever try to write a pattern `release-*` like how the branch protection allows us to do. But one INFRA member told me that it's not yet supported by the `.asf.yaml`.

May I ask where is the release process documented?

**Comment by gyfora** [comment]
@tisonkun if you could add it here please: https://cwiki.apache.org/confluence/display/FLINK/Creating+a+Flink+Kubernetes+Operator+Release

Thank you!

**Comment by tisonkun** [comment]
@gyfora Updated: https://cwiki.apache.org/confluence/pages/diffpagesbyversion.action?pageId=199540570&selectedPageVersions=16&selectedPageVersions=15

**Pull request merged**
