### PR TITLE
[FLINK-29283] Remove hardcoded apiVersion from operator unit test

### PR DESCRIPTION
**Pull request by Huangxuny1**
## What is the purpose of the change

- Remove hardcoded apiVersion from operator unit test

## Brief change log

Modified `ReconciliationUtilsTest#testSpecSerializationWithVersion`

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no) `no`
  - The public API, i.e., is any changes to the `CustomResourceDescriptors`: (yes / no) `no`
  - Core observer or reconciler logic that is regularly executed: (yes / no) `no`

## Documentation

  - Does this pull request introduce a new feature? (yes / no)  `no`
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) `no`

### CODE REVIEW

**Comment by morhidi** [comment]
There are a couple places in the unit tests where things are intentionally kept as hardcoded strings to raise attention for significant/breaking changes. CRD version is such, I assume @gyfora has left this one there for a purpose.

**Comment by gyfora** [comment]
Having hard coded versions serve as a basic form of backward compatibility test . I think we should not change these.

**Comment by gyfora** [comment]
Later if we feel like it we can parameterize these tests when new versions come around that change the serialization logic

**Comment by gyfora** [comment]
I am closing this PR

**Pull request closed without merging**
