### PR TITLE
FLINK-27746: Remove COPY .git in dockerfile

### PR DESCRIPTION
**Pull request by tisonkun**
As build process doesn't depend on those files.

Signed-off-by: tison <wander4096@gmail.com>

### CODE REVIEW

**Comment by morhidi** [comment]
cc @SteNicholas I guess this was part of FLINK-27124] Flink Kubernetes operator prints starting logs with corrent version

**Comment by tisonkun** [comment]
@morhidi thanks for pointing this out. Then I think @SteNicholas can handle this whole story properly. Closed as lack of background.

Although, an insight is that we may use another approach to generate git.property since the released tarball normally excludes `.git` artifacts (or we'd like to include them?).

**Comment by morhidi** [comment]
cc @wangyang0918 WDYT?

**Comment by wangyang0918** [comment]
I lean to skip copying the `.git` directory if not exist. Then the version in log will be `UNKNOWN` if building the image with source release.

**Pull request closed without merging**
