### PR TITLE
[FLINK-33403] Bump flink version to 1.18.1 for flink-kubernetes-operator

### PR DESCRIPTION
**Pull request by 1996fanrui**
## What is the purpose of the change

Bump flink version to 1.18.1 for flink-kubernetes-operator

## Brief change log

- Bump flink version to 1.18.1 for flink-kubernetes-operator
- Using the latest shaded guava31
- Support the latest `KubernetesClusterDescriptor`
- Remove rescale api related classes

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): yes
  - The public API, i.e., is any changes to the `CustomResourceDescriptors`:  no
  - Core observer or reconciler logic that is regularly executed: no

## Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by 1996fanrui** [comment]
Hi @gyfora , the flink-kubernetes-operator has 3 overlapping classes with 1.17.1, but has 10  overlapping classes, so the CI fails.

I'd like to check with you what types of classes should be redefined in `flink-kubernetes-operator`? Should we change the CI check or remove them in this PR? I see these classes are similar with flink.

For `JobResourceRequirementsBody` related classes, I guess we define them due to 1.18 isn't released before, but `flink-kubernetes-operator` needs to use them, right? If yes, should we remove them now?

```
Warning:  flink-kubernetes-operator-1.7-SNAPSHOT.jar, flink-runtime-1.17.1.jar define 3 overlapping classes: 
Warning:    - org.apache.flink.runtime.rest.messages.job.savepoints.SavepointTriggerRequestBody
Warning:    - org.apache.flink.runtime.rest.messages.job.savepoints.stop.StopWithSavepointRequestBody
Warning:    - org.apache.flink.runtime.rest.messages.job.metrics.IOMetricsInfo



Warning:  flink-kubernetes-operator-1.7-SNAPSHOT.jar, flink-runtime-1.18.0.jar define 10 overlapping classes: 
Warning:    - org.apache.flink.runtime.jobgraph.JobVertexResourceRequirements$Parallelism
Warning:    - org.apache.flink.runtime.rest.messages.job.savepoints.SavepointTriggerRequestBody
Warning:    - org.apache.flink.runtime.rest.messages.job.savepoints.stop.StopWithSavepointRequestBody
Warning:    - org.apache.flink.runtime.jobgraph.JobVertexResourceRequirements
Warning:    - org.apache.flink.runtime.rest.messages.job.metrics.IOMetricsInfo
Warning:    - org.apache.flink.runtime.rest.messages.job.JobResourceRequirementsHeaders
Warning:    - org.apache.flink.runtime.jobgraph.JobResourceRequirements
Warning:    - org.apache.flink.runtime.jobgraph.JobResourceRequirements$Builder
Warning:    - org.apache.flink.runtime.rest.messages.job.JobResourcesRequirementsUpdateHeaders
Warning:    - org.apache.flink.runtime.rest.messages.job.JobResourceRequirementsBody
```

**Comment by gyfora** [comment]
In the past we have only bumped Flink version when the first patch release was out. There are usually a few compatibility issues that come out and need to be fixed some of them are not always immediately apparent.

I suggest we delay this until 1.18.1 as this doesn’t provide clear value at the moment @1996fanrui

**Comment by gyfora** [comment]
> Hi @gyfora , the flink-kubernetes-operator has 3 overlapping classes with 1.17.1, but has 10 overlapping classes, so the CI fails.
> 
> I'd like to check with you what types of classes should be redefined in `flink-kubernetes-operator`? Should we change the CI check or remove them in this PR? I see these classes are similar with flink.
> 
> For `JobResourceRequirementsBody` related classes, I guess we define them due to 1.18 isn't released before, but `flink-kubernetes-operator` needs to use them, right? If yes, should we remove them now?
> 
> ```
> Warning:  flink-kubernetes-operator-1.7-SNAPSHOT.jar, flink-runtime-1.17.1.jar define 3 overlapping classes: 
> Warning:    - org.apache.flink.runtime.rest.messages.job.savepoints.SavepointTriggerRequestBody
> Warning:    - org.apache.flink.runtime.rest.messages.job.savepoints.stop.StopWithSavepointRequestBody
> Warning:    - org.apache.flink.runtime.rest.messages.job.metrics.IOMetricsInfo
> 
> 
> 
> Warning:  flink-kubernetes-operator-1.7-SNAPSHOT.jar, flink-runtime-1.18.0.jar define 10 overlapping classes: 
> Warning:    - org.apache.flink.runtime.jobgraph.JobVertexResourceRequirements$Parallelism
> Warning:    - org.apache.flink.runtime.rest.messages.job.savepoints.SavepointTriggerRequestBody
> Warning:    - org.apache.flink.runtime.rest.messages.job.savepoints.stop.StopWithSavepointRequestBody
> Warning:    - org.apache.flink.runtime.jobgraph.JobVertexResourceRequirements
> Warning:    - org.apache.flink.runtime.rest.messages.job.metrics.IOMetricsInfo
> Warning:    - org.apache.flink.runtime.rest.messages.job.JobResourceRequirementsHeaders
> Warning:    - org.apache.flink.runtime.jobgraph.JobResourceRequirements
> Warning:    - org.apache.flink.runtime.jobgraph.JobResourceRequirements$Builder
> Warning:    - org.apache.flink.runtime.rest.messages.job.JobResourcesRequirementsUpdateHeaders
> Warning:    - org.apache.flink.runtime.rest.messages.job.JobResourceRequirementsBody
> ```

yes the resource rest api classes can be removed with this change

**Comment by 1996fanrui** [comment]
> In the past we have only bumped Flink version when the first patch release was out. There are usually a few compatibility issues that come out and need to be fixed some of them are not always immediately apparent.
> 
> I suggest we delay this until 1.18.1 as this doesn’t provide clear value at the moment @1996fanrui

Thanks @gyfora for the explanation.

If so, I can go ahead after 1.18.1 is released.

**Comment by 1996fanrui** [comment]
Hi @gyfora , this PR is done for now due to 1.18.1 is released. Please help take a look in your free time, thanks~

**Review by gyfora — APPROVED** [review]
looks good!

**Comment by 1996fanrui** [comment]
Thanks for the quick review, merging~

**Pull request merged**
