### PR TITLE
[BP-0.1] [FLINK-26903] Add correct NOTICE file to flink-kubernetes-operator

### PR DESCRIPTION
**Pull request by wangyang0918**
Backport #125 to release-0.1 branch

### CODE REVIEW

**Comment by wangyang0918** [comment]
Will merge this PR after CI passed.

**Comment by zentol** [comment]
Having the jars contain the NOTICE files is imo insufficient as discoverability within the image is basically 0. You should extract & merge the NOTICE files for all jars, similarly to what we do for flink-dist.

**Comment by gyfora** [comment]
@zentol we could include this in the notice for the operator as well, but since the jars contain the notices themselves we don't really need to do this. Anyone checking the contents of the container should be able to discover these notices. Thet are not part of any bundle that we publist to dist.apache.org.

**Comment by gyfora** [comment]
We can open a jira for this to make it nicer for 1.0.0 together with other NOTICE improvements

**Comment by wangyang0918** [comment]
I have created a ticket FLINK-26914 to track the NOTICE file improvements.

**Comment by mbalassi** [comment]
@zentol thanks for looking into this. I agree that the current setup could be improved, and support @wangyang0918's suggestion to solve this for 1.0.0, and live with it for 0.1.0.

**Pull request merged**
