### PR TITLE
[FLINK-27728] Adding os update to debian image

### PR DESCRIPTION
**Pull request by jbusche**
Signed-off-by: James Busche <jbusche@us.ibm.com>

When the flink-kubernetes-operator is build with the:
```
RUN apt-get update
RUN apt-get upgrade -y
```
Then  four current vulnerabilities will be solved.  This will likely help solve many future upcoming OS vulnerabilities as they become known and solved in the near future.

### CODE REVIEW

**Comment by gyfora** [comment]
Is this linked to any jira?

Seems like the docker build doesnt run:
```
Error: buildx bake failed with: error: failed to solve: process "/dev/.buildkit_qemu_emulator /bin/sh -c apt-get upgrade -y" did not complete successfully: exit code: 100
```

**Comment by gyfora** [comment]
Please add [FLINK-27728] to both the PR and the commit message as a prefix that will help us review :)

**Comment by jbusche** [comment]
Yes, thanks @gyfora, I'll do that going forward.  It's interesting, it builds locally, but not on github.  Didn't know how to try a re-run, so added a comment and trying again to see if it maybe was a one-time thing....

**Comment by gyfora** [comment]
I also triggered the github action manually, it seems like a persistent issue. 

I cannot reproduce it locally, where it works fine on my M1 macbook

**Comment by gyfora** [comment]
looping in @mbalassi and @morhidi , they know this stuff much better than me

**Comment by mbalassi** [comment]
Good catch, @jbusche. I hope the issue is as simple as suggested here:

https://stackoverflow.com/questions/38002543/apt-get-update-returned-a-non-zero-code-100

Could you try
```
RUN apt-get update && apt-get install -y apt-transport-https
```
In line 78 please?

**Comment by jbusche** [comment]
Shoot, that didn't seem to help.  Still looks good for my local build.  I can try again tomorrow.  Thanks @mbalassi

**Comment by mbalassi** [comment]
Seems I found the missing piece:

https://github.com/mbalassi/flink-kubernetes-operator/runs/6541402938?check_suite_focus=true
https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images

We needed this anyway.

**Comment by gyfora** [comment]
After @mbalassi 's fix maybe we dont need ` && apt-get install -y apt-transport-https` anymore

**Pull request closed without merging**
