### PR TITLE
[FLINK-26612] Set up Flink Kubernetes Operator Document Website

### PR DESCRIPTION
**Pull request by mbalassi**
Based on yunfengzhou-hub's work in https://github.com/apache/flink-ml/commit/1618e6dccf8265fa0622c249d5218f53df8a2d57.

This contains the general tooling for the Flink docs, a quickstart page and a skeleton for future minimal content based on FLINK-26509 and FLINK-26612

### CODE REVIEW

**Comment by morhidi** [comment]
+1 LGTM

**Comment by wangyang0918** [comment]
Great work. Where could I find the website?

**Comment by gyfora** [comment]
@wangyang0918 we still probably need some steps to hook it up to the Flink webpage, but we should first add the bulk of the content I think. We will work on in it this week.

**Comment by wangyang0918** [comment]
Sounds great.

**Pull request merged**
