### PR TITLE
[FLINK-36170] bump assert4j version

### PR DESCRIPTION
**Pull request by r-sidd**
Bump the **assertj-core** version to remediate vulnerabilities on the dependant packages.

Package info:

https://mvnrepository.com/artifact/org.assertj/assertj-core/3.26.3

change info:

https://github.com/r-sidd/flink-kubernetes-operator/blob/main/pom.xml#L99

### CODE REVIEW

**Review by 1996fanrui — APPROVED** [review]
Thanks @r-sidd for the contribution!

LGTM.

I will merge it if no objection within 24 hours.

**Comment by r-sidd** [comment]
> Thanks @r-sidd for the contribution!
> 
> LGTM.
> 
> I will merge it if no objection within 24 hours.

Sure, thank you 🙂

**Comment by gyfora** [comment]
@1996fanrui it's okay to merge these types of straightforward changes immediately 👍

**Comment by 1996fanrui** [comment]
> @1996fanrui it's okay to merge these types of straightforward changes immediately 👍

Thanks for the reminder, merging~

**Pull request merged**
