### PR TITLE
[FLINK-27005][FLINK-27065] Bump api version + store last spec as string

### PR DESCRIPTION
**Pull request by gyfora**
This PR contains two (related) changes:

1. Bump the CRD version to v1beta1 (without keeping the old one) and updating examples/docs related to this
2. Change the status field in the CRD to store the lastReconciledSpec in a JSON string form instead object.

You can see an example of the resulting status:

```
Status:
  Job Manager Deployment Status:  DEPLOYING
  Job Status:
    Savepoint Info:
    State:  UNKNOWN
  Reconciliation Status:
    Last Reconciled Spec:  {
  "image" : "flink:1.14",
  "imagePullPolicy" : null,
  "serviceAccount" : "flink",
  "flinkVersion" : "v1_14",
  "ingress" : null,
  "flinkConfiguration" : {
    "taskmanager.numberOfTaskSlots" : "2"
  },
  "podTemplate" : null,
  "jobManager" : {
    "resource" : {
      "cpu" : 1.0,
      "memory" : "2048m"
    },
    "replicas" : 1,
    "podTemplate" : null
  },
  "taskManager" : {
    "resource" : {
      "cpu" : 1.0,
      "memory" : "2048m"
    },
    "podTemplate" : null
  },
  "job" : {
    "jarURI" : "local:///opt/flink/examples/streaming/StateMachineExample.jar",
    "parallelism" : 2,
    "entryClass" : null,
    "args" : [ [],
    "state" : "running",
    "savepointTriggerNonce" : null,
    "initialSavepointPath" : null,
    "upgradeMode" : "stateless"
  },
  "restartNonce" : null,
  "logConfiguration" : null
}
    Success:  true
```

### CODE REVIEW

**Comment by wangyang0918** [comment]
Hmm. I prefer to store the lastReconciledSpec without spaces, line break, etc. since we are showing a json in a yaml format.

```
Last Reconciled Spec: {"image":"flink:1.14","imagePullPolicy":null,"serviceAccount":"flink","flinkVersion":"v1_14","ingress":null,"flinkConfiguration":{"taskmanager.numberOfTaskSlots":"2"},"podTemplate":null,"jobManager":{"resource":{"cpu":1,"memory":"2048m"},"replicas":1,"podTemplate":null},"taskManager":{"resource":{"cpu":1,"memory":"2048m"},"podTemplate":null},"job":{"jarURI":"local:///opt/flink/examples/streaming/StateMachineExample.jar","parallelism":2,"entryClass":null,"args":[],"state":"running","savepointTriggerNonce":null,"initialSavepointPath":null,"upgradeMode":"stateless"},"restartNonce":null,"logConfiguration":null}
```

**Comment by gyfora** [comment]
> Hmm. I prefer to store the lastReconciledSpec without spaces, line break, etc. since we are showing a json in a yaml format.
> 
> ```
> Last Reconciled Spec: {"image":"flink:1.14","imagePullPolicy":null,"serviceAccount":"flink","flinkVersion":"v1_14","ingress":null,"flinkConfiguration":{"taskmanager.numberOfTaskSlots":"2"},"podTemplate":null,"jobManager":{"resource":{"cpu":1,"memory":"2048m"},"replicas":1,"podTemplate":null},"taskManager":{"resource":{"cpu":1,"memory":"2048m"},"podTemplate":null},"job":{"jarURI":"local:///opt/flink/examples/streaming/StateMachineExample.jar","parallelism":2,"entryClass":null,"args":[],"state":"running","savepointTriggerNonce":null,"initialSavepointPath":null,"upgradeMode":"stateless"},"restartNonce":null,"logConfiguration":null}
> ```

@wangyang0918 taht would be trivial to change, I thought this looks better for the user to read but otherwise I dont have a strong preference

**Comment by wangyang0918** [comment]
I will have a try on this PR later.

**Comment by tweise** [comment]
@gyfora it might also be good to capture the version of the spec that is stored in "Last Reconciled Spec"? That way it would be possible to deserialize older status fields after incompatible spec changes.

**Comment by gyfora** [comment]
@tweise that makes sense, I will try to see how to add the extra version field

**Comment by gyfora** [comment]
Updated the logic now it looks like this:
```
    Last Reconciled Spec:  {"image":"flink:1.14","imagePullPolicy":null,"serviceAccount":"flink","flinkVersion":"v1_14","ingress":null,"flinkConfiguration":{"taskmanager.numberOfTaskSlots":"2"},"podTemplate":null,"jobManager":{"resource":{"cpu":1.0,"memory":"2048m"},"replicas":1,"podTemplate":null},"taskManager":{"resource":{"cpu":1.0,"memory":"2048m"},"podTemplate":null},"job":{"jarURI":"local:///opt/flink/examples/streaming/StateMachineExample.jar","parallelism":2,"entryClass":null,"args":[],"state":"running","savepointTriggerNonce":null,"initialSavepointPath":null,"upgradeMode":"stateless"},"restartNonce":null,"logConfiguration":null,"apiVersion":"v1beta1"}
```
Note the extra `apiVersion` field at the end. 

@wangyang0918 @tweise PTAL again :)

**Review by wangyang0918 — APPROVED** [review]
Verified locally and it works well.
* Suspend all the running FlinkDeployment
* Uninstall the flink-kubernetes-operator with version `v1alpha1`
* Delete the old crds manually
* Update the apiversion of existing FlinkDeployment to `v1beta1`
* Install the flink-kubernetes-operator with version `v1beta1`
* Resume all the FlinkDeployment

Maybe we need to add a simple statement of version upgrading in the README, just like https://github.com/GoogleCloudPlatform/spark-on-k8s-operator#project-status.

**Comment by gyfora** [comment]
Merging this, I think https://issues.apache.org/jira/browse/FLINK-26811 will cover the doc change :)

**Pull request merged**
