### PR TITLE
[FLINK-27595] Helm - made security context configurable

### PR DESCRIPTION
**Pull request by haoxins**

### CODE REVIEW

**Review by mbalassi — APPROVED** [review]
Thanks, LGTM.

**Comment by morhidi** [comment]
LGTM too. It maybe worth defining separate securityContext at container level (webhook/operator) too with an empty body `{}`.

**Comment by haoxins** [comment]
> LGTM too. It maybe worth defining separate securityContext at container level (webhook/operator) too with an empty body `{}`.

added

**Comment by morhidi** [comment]
thanks, +1 for merging

**Review by wangyang0918 — APPROVED** [review]
+1.

Merging now

**Pull request merged**
