### PR TITLE
[FLINK-28574] Bump the fabric8 kubernetes-client to 5.12.3

### PR DESCRIPTION
**Pull request by SteNicholas**
## What is the purpose of the change

The current fabric8 kubernetes-client(5.5.0) will swallow the KubernetesClientException and then the next renewing could not work properly until reach the deadline. This will be a serious problem because one time failure of renewing leader annotation will cause leadership lost. Bump the fabric8 kubernetes-client to 5.12.3

## Brief change log

  - Bump the fabric8 kubernetes-client to 5.12.3
  - Bump the Java Operator SDK to 3.1.1

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changes to the `CustomResourceDescriptors`: (yes / **no**)
  - Core observer or reconciler logic that is regularly executed: (yes / **no**)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by gyfora** [comment]
Hey @SteNicholas 

I took a quick look at the NOTICE file updates and I see a few inconsistencies.

These are the dependencies that we bundle into our shaded jar:

```
com.esotericsoftware.kryo:kryo:jar:2.24.0
com.esotericsoftware.minlog:minlog:jar:1.2
com.fasterxml.jackson.core:jackson-annotations:jar:2.13.2
com.fasterxml.jackson.core:jackson-core:jar:2.13.2
com.fasterxml.jackson.core:jackson-databind:jar:2.13.2.2
com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.13.2
com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.2
com.github.mifmif:generex:jar:1.0.2
com.google.code.findbugs:jsr305:jar:1.3.9
com.squareup.okhttp3:logging-interceptor:jar:4.10.0
com.squareup.okhttp3:okhttp:jar:4.10.0
com.squareup.okio:okio-jvm:jar:3.0.0
com.squareup:javapoet:jar:1.13.0
com.twitter:chill-java:jar:0.7.6
commons-cli:commons-cli:jar:1.5.0
commons-collections:commons-collections:jar:3.2.2
commons-io:commons-io:jar:2.11.0
dk.brics.automaton:automaton:jar:1.11-8
io.fabric8:kubernetes-client:jar:5.12.3
io.fabric8:kubernetes-model-admissionregistration:jar:5.12.3
io.fabric8:kubernetes-model-apiextensions:jar:5.12.3
io.fabric8:kubernetes-model-apps:jar:5.12.3
io.fabric8:kubernetes-model-autoscaling:jar:5.12.3
io.fabric8:kubernetes-model-batch:jar:5.12.3
io.fabric8:kubernetes-model-certificates:jar:5.12.3
io.fabric8:kubernetes-model-common:jar:5.12.3
io.fabric8:kubernetes-model-coordination:jar:5.12.3
io.fabric8:kubernetes-model-core:jar:5.12.3
io.fabric8:kubernetes-model-discovery:jar:5.12.3
io.fabric8:kubernetes-model-events:jar:5.12.3
io.fabric8:kubernetes-model-extensions:jar:5.12.3
io.fabric8:kubernetes-model-flowcontrol:jar:5.12.3
io.fabric8:kubernetes-model-metrics:jar:5.12.3
io.fabric8:kubernetes-model-networking:jar:5.12.3
io.fabric8:kubernetes-model-node:jar:5.12.3
io.fabric8:kubernetes-model-policy:jar:5.12.3
io.fabric8:kubernetes-model-rbac:jar:5.12.3
io.fabric8:kubernetes-model-scheduling:jar:5.12.3
io.fabric8:kubernetes-model-storageclass:jar:5.12.3
io.fabric8:zjsonpatch:jar:0.3.0
io.javaoperatorsdk:operator-framework-core:jar:3.1.1
io.javaoperatorsdk:operator-framework:jar:3.1.1
org.apache.commons:commons-compress:jar:1.21
org.apache.commons:commons-lang3:jar:3.12.0
org.apache.commons:commons-math3:jar:3.6.1
org.apache.logging.log4j:log4j-1.2-api:jar:2.17.1
org.apache.logging.log4j:log4j-api:jar:2.17.1
org.apache.logging.log4j:log4j-core:jar:2.17.1
org.apache.logging.log4j:log4j-slf4j-impl:jar:2.17.1
org.javassist:javassist:jar:3.24.0-GA
org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.5.31
org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.6.10
org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.6.10
org.jetbrains.kotlin:kotlin-stdlib:jar:1.6.20
org.jetbrains:annotations:jar:13.0
org.lz4:lz4-java:jar:1.8.0
org.objenesis:objenesis:jar:2.1
org.slf4j:slf4j-api:jar:1.7.36
org.xerial.snappy:snappy-java:jar:1.1.8.3
org.yaml:snakeyaml:jar:1.30
```

Could you please update the list based on this and remove the unnecessary ones?

**Comment by gyfora** [comment]
This is based on the command:
```
mvn clean install -DskipTests -pl flink-kubernetes-operator | grep Including | grep -v org.apache.flink | cut -d' ' -f3 | sort
```

**Comment by SteNicholas** [comment]
@gyfora, I have double checked the NOTICE dependencies list and updated the list based on the above command output. PTAL.

**Review by gyfora — APPROVED** [review]
Looks good! Thank you :)

**Pull request merged**
