### PR TITLE
[FLINK-26637] Document Basic Concepts and Architecture

### PR DESCRIPTION
**Pull request by morhidi**
- added overview and features page
- added architecture page
- architecture diagram
image
- control loop diagram
image

### CODE REVIEW

**Comment by morhidi** [comment]
cc @gyfora @wangyang0918 @bgeng777 . Wanted to share this content still in wip to get some early feedbacks on the architecture diagram, feature summary.

**Comment by wangyang0918** [comment]
It will help a lot when reviewing if you could attach the picture directly in the PR.

**Comment by morhidi** [comment]
> It will help a lot when reviewing if you could attach the picture directly in the PR.

@wangyang0918 just added to the comments

**Comment by gyfora** [comment]
@wangyang0918 you can get a rendered preview by clicking on the page icon on the top left for each file:
image

**Comment by gyfora** [comment]
Thank you Matyas, I think this is an excellent starting point for further content. I am going to merge this and we can tackle improvements / additions in later tickets.

**Pull request merged**
