### PR TITLE
[FLINK-34934] Translation Flink-Kubernetes-Operator document framework construction

### PR DESCRIPTION
**Pull request by caicancai**
## What is the purpose of the change
https://issues.apache.org/jira/browse/FLINK-34934

Build the Flink-Kubernetes-Operator document translation framework, and subsequently translate English documents one by one.

## Brief change log

Copy all documentations to content.zh folder, and add the English and Chinese（中文版） button.

### CODE REVIEW

**Comment by caicancai** [comment]
This is a PR to build a translation framework. After the subsequent merger, I will translate the documents one by one. Thank you.

**Comment by caicancai** [comment]
cc @1996fanrui

**Comment by 1996fanrui** [comment]
Thanks @caicancai for the contribution!

This PR didn't add the Chinese version and English version in this PR, right? 

image

**Comment by caicancai** [comment]
> Thanks @caicancai for the contribution!
> 
> This PR didn't add the Chinese version and English version in this PR, right?
> 
> image

It seems that the config.toml of flink-kubernetes-operator is different from the config.toml of flink. I don’t know how to modify it, sorry.

**Comment by caicancai** [comment]
@1996fanrui  done
2024-03-27 21-24-15屏幕截图

**Review by 1996fanrui — CHANGES_REQUESTED** [review]
Thanks @caicancai  for the contribution and test!

I run hugo locally, and try to choose English and Chinese doc, it works well.

But I noticed https://github.com/apache/flink-kubernetes-operator/pull/807 is merged, but this PR doesn't include it for Chinese doc. It's needed to sync them from English doc to Chinese doc.

After that, this PR is fine for me.

**Comment by caicancai** [comment]
> Thanks @caicancai for the contribution and test!
> 
> I run hugo locally, and try to choose English and Chinese doc, it works well.
> 
> But I noticed #807 is merged, but this PR doesn't include it for Chinese doc. It's needed to sync them from English doc to Chinese doc.
> 
> After that, this PR is fine for me.

Thank you for the reminder, updated

**Review by 1996fanrui — APPROVED** [review]
LGTM, assuming the CI is green.

cc @gyfora  @mxm , would you like to review this PR as well? It only builds the Flink-Kubernetes-Operator document framework for Chinese version, and subsequently translate English documents one by one.

This PR copied all documentations to `content.zh` folder, and add the English and Chinese（中文版） button.

BTW, after this PR is merged, all PRs need to update both of English and Chinese doc. Chinese doc can be written via English first, and Chinese contributors can translate them later.

**Pull request merged**
