### PR TITLE
[FLINK-27852] Add OLM bundle generator

### PR DESCRIPTION
**Pull request by tedhtchang**
Signed-off-by: ted chang <htchang@us.ibm.com>

## What is the purpose of the change

This pull request adds scripts to generate OLM bundle from the helm chart.

## Brief change log

- Add scripts to generate and test the OLM bundle.
- Document the scripts and OLM bundle CI tests.

## Verifying this change

The AutomatedOLMBuildAndDeploy.sh script will generate the bundle and deploy the Flink Kubernetes Operator locally.

## Does this pull request potentially affect one of the following parts:

No

## Documentation

No

### CODE REVIEW

**Comment by tedhtchang** [comment]
@morhidi @gyfora

**Comment by gyfora** [comment]
cc @gaborgsomogyi

**Comment by tedhtchang** [comment]
Hi @morhidi thanks for review! Which base image would you recommend ?

**Comment by morhidi** [comment]
> Hi @morhidi thanks for review! Which base image would you recommend ?

I've no preference, use whatever you feel is the best fit for these scripts to run properly. Please make sure though that the base image is multi arch and contains `arm64` too.

**Comment by morhidi** [comment]
Please also rebase to the latest main version, e2es has been fixed recently

**Comment by tedhtchang** [comment]
Hi @morhidi I can't find a mac os w/ m1 right now. If you have one could you run the new ./generate-olm-bundle.sh script and see if this what we want?

**Comment by morhidi** [comment]
Hi @tedhtchang this looks better now however I guess this was unintentional:
```
+ docker push docker.io/tedhtchang/flink-op-bundle:1.3.0
The push refers to repository [docker.io/tedhtchang/flink-op-bundle]
893500a83403: Preparing
ba0bcc7ff5c8: Preparing
denied: requested access to the resource is denied
```

**Comment by morhidi** [comment]
We should add the generated folders to .gitignore:
```
	1.3.0/
	cat/
	crds/
	helm/
```

Maybe it's even better to put these behind a single `generated` or `target` or sg similar folder.

**Comment by morhidi** [comment]
> Hi @morhidi I can't find a mac os w/ m1 right now. If you have one could you run the new ./generate-olm-bundle.sh script and see if this what we want?

It works on m1 thanks.

**Comment by tedhtchang** [comment]
Hi @morhidi Could you test on a m1 mac again. Thanks.

**Comment by morhidi** [comment]
> Hi @morhidi Could you test on a m1 mac again. Thanks.

will do thanks!

**Comment by morhidi** [comment]
> > Hi @morhidi Could you test on a m1 mac again. Thanks.
> 
> will do thanks!

I'm now getting on mac os with zsh:

```
(minikube:default)  ➜  olm git:(FLINK-27852) ./generate-olm-bundle.sh
tr: Illegal byte sequence
(minikube:default)  ➜  olm git:(FLINK-27852) source env.sh
tr: Illegal byte sequence
```

**Comment by morhidi** [comment]
> > > Hi @morhidi Could you test on a m1 mac again. Thanks.
> > 
> > 
> > will do thanks!
> 
> I'm now getting on mac os with zsh:
> 
> ```
> (minikube:default)  ➜  olm git:(FLINK-27852) ./generate-olm-bundle.sh
> tr: Illegal byte sequence
> (minikube:default)  ➜  olm git:(FLINK-27852) source env.sh
> tr: Illegal byte sequence
> ```

Try using something like this:
```
(minikube:default)  ➜  olm git:(FLINK-27852) head -c24 < /dev/random | base64
ATgq7rlRefHs+pPE4twDn0XmDctHhU4o
```

**Comment by morhidi** [comment]
> > > > Hi @morhidi Could you test on a m1 mac again. Thanks.
> > > 
> > > 
> > > will do thanks!
> > 
> > 
> > I'm now getting on mac os with zsh:
> > ```
> > (minikube:default)  ➜  olm git:(FLINK-27852) ./generate-olm-bundle.sh
> > tr: Illegal byte sequence
> > (minikube:default)  ➜  olm git:(FLINK-27852) source env.sh
> > tr: Illegal byte sequence
> > ```
> 
> Try using something like this:
> 
> ```
> (minikube:default)  ➜  olm git:(FLINK-27852) head -c24 < /dev/random | base64
> ATgq7rlRefHs+pPE4twDn0XmDctHhU4o
> ```

rc: https://unix.stackexchange.com/questions/45404/why-cant-tr-read-from-dev-urandom-on-osx

**Comment by tedhtchang** [comment]
@morhidi How about this? `head -c24 < /dev/random|base64|tr -dc "[:lower:]"|head -c24`

**Comment by morhidi** [comment]
> @morhidi How about this? `head -c24 < /dev/random|base64|tr -dc "[:lower:]"|head -c24`

lik in the good old days :) I guess we can ignore the percentage character which is a zsh 'thing'

````
(minikube:default)  ➜  olm git:(FLINK-27852) head -c24 < /dev/random|base64|tr -dc "[:lower:]"|head -c24
pwhtwbmibjwmd%
```

**Comment by tedhtchang** [comment]
@morhidi  It should be fine. `%` means output has no trailing new line. ie. `echo -n hello`

**Comment by tedhtchang** [comment]
@morhidi

**Pull request merged**
