### PR TITLE
[FLINK-30669] update recent job status in flinkdeployment object

### PR DESCRIPTION
**Pull request by kmozaid**
JIRA: https://issues.apache.org/jira/browse/FLINK-30669

## What is the purpose of the change

This pull request fix an issue where incorrect job status is updated in FlinkDeployment resource.

### CODE REVIEW

**Comment by gyfora** [comment]
I don't really see the value of this fix as the core operator logic such as observe/upgrades etc won't work when there are multiple jobs in a single application.

**Comment by litiliu** [comment]
> I don't really see the value of this fix as the core operator logic such as observe/upgrades etc won't work when there are multiple jobs in a single application.

Are we going to support running multiple jobs in a single application?   There are some use case to submitting multiple pipelines in the loop within the same batch job.  Then using the `state` field in `jobStatus` to query whether all the pipeline in that batch job has finished.

**Comment by gyfora** [comment]
@litiliu multiple job support is not on our roadmap. In general we are not focusing on batch processing specific features currently.

**Comment by kmozaid** [comment]
Hi @gyfora IMHO, this is very minimalistic change which does not alter any existing flow. As you can see, in [ApplicationObserver.java](https://github.com/apache/flink-kubernetes-operator/pull/504/files#diff-7bd417adb2e95b5e8b81371d3022fa637a74a0a1a96403fbcc5cc5049a4df379) , just added sorting but still picks only one element from list and in `JobStatusObserver` adding if condition on jobid equality also does not change anything existing.

I have tested these changes. you could initiate workflows to see that it works fine.

**Comment by kmozaid** [comment]
> I don't really see the value of this fix as the core operator logic such as observe/upgrades etc won't work when there are multiple jobs in a single application.

When there are multiple jobs running in sequence, everything works fine.

**Comment by gyfora** [comment]
I agree @kmozaid if this doesn't affect existing jobs and improves some others then the change makes sense :) 

Could you please add a unit test to guard this change against possible future regressions?

**Comment by kmozaid** [comment]
> I agree @kmozaid if this doesn't affect existing jobs and improves some others then the change makes sense :)
> 
> Could you please add a unit test to guard this change against possible future regressions?

sure, let me add a test.

**Comment by litiliu** [comment]
@gyfora 2 workflows awaiting approval. Could you help to approve it?

**Pull request merged**
