### PR TITLE
[FLINK-29383] Add PrinterColumn annotation for status fields

### PR DESCRIPTION
**Pull request by haoxins**
## What is the purpose of the change

Add `PrinterColumn` annotation to the state fields, so that we can use `k get flinksession -o wide` to see session job list with status fields.

## Brief change log

- Add `@PrinterColumn` annotation to the state fields

## Verifying this change

I think the generated CRDs have covered the change 

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changes to the `CustomResourceDescriptors`: (no)
  - Core observer or reconciler logic that is regularly executed: (yes / no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by gyfora** [comment]
What do you think @tweise @morhidi , to me this feels a little arbitrary why expose those specific fields. Might mislead the users.

**Comment by gyfora** [comment]
I think if users care about certain specific status fields (which are anyways internal to the operator logic) they could simply modify the CRD that they install with these properties. Adding a doc guide instead of hardcoding it might be more helpful, not sure...

**Comment by gyfora** [comment]
I agree with @tweise , I think if you want adding some documentation on how to this would be ok. Or we could simply close this ticket, up to you

**Comment by morhidi** [comment]
I've no objection against this, it'd be great to see the lifecycle state there as well:)

**Comment by haoxins** [comment]
When I have a lot of session jobs, this will be useful to figure out which one meets error.
This is what I'm facing when I submit hundreds of session jobs.

I can use `k get flinksessionjobs -o wide | grep xxx` to filter the jobs with problems,
and then debug what is wrong.

**Comment by haoxins** [comment]
The other popular apps such as Argo CD also includes special status fields. such as
```
k get app -o wide -n argocd
NAME                   SYNC STATUS   HEALTH STATUS   REVISION
my-app-1             Synced               Healthy                   b3288befa7789047ff06c7e8631cbb65185ea3fe
```
I think the users of the Flink operator should also get familiar with these status fields' meanings.

**Comment by haoxins** [comment]
1. the use case is to filter out the jobs with problems
2. and these fields are the most helpful ones

This is the reason why we need these additional printer columns

**Comment by haoxins** [comment]
I just read another Jira issue about this https://issues.apache.org/jira/browse/FLINK-27893, it is worth discussing which fields should be exposed.

But the status fields are beneficial for deployment and debugging, and we can change the print fields without compatibility concerns.

I mean we can expose these now and change in the future base on the users feedback?

**Comment by gyfora** [comment]
Since it doesn’t introduce new things to the status I think this is ok on a second thought :)

**Comment by gyfora** [comment]
@tweise any objections against merging this based on the additional input?

**Comment by tweise** [comment]
No objections. How would we accommodate another request that prefers some different columns though :)

**Comment by gyfora** [comment]
> No objections. How would we accommodate another request that prefers some different columns though :)

We could then start to prioritize some fields and limit it to a fairly small number of total extra fields. But so far people did not seem to be too interested in these print columns :)

**Pull request merged**
