### PR TITLE
[FLINK-26914] Various improvements for notice and license files

### PR DESCRIPTION
**Pull request by wangyang0918**
The `flink-kubernetes-shaded-*.jar` does not have a correct NOTICE before. e05ee2c84d91f84442ecec761633d93217d272eb fixes this. This commit also removes the explicit flink dependencies from NOTICE since it will be automatically merged by `ApacheNoticeResourceTransformer`.

This PR then introduces the bundled collected NOTICE and licenses. They are located under `/flink-kubernetes-opeartor` in the docker image.  Now they could be very easily found.

```
flink@flink-kubernetes-operator-68f9d986c5-2rbv4:/flink-kubernetes-operator$ pwd
/flink-kubernetes-operator
flink@flink-kubernetes-operator-68f9d986c5-2rbv4:/flink-kubernetes-operator$ ls -l
total 122920
-rw-r--r-- 1 root  root      62061 May 15 01:33 NOTICE
-rw-r--r-- 1 flink flink 112844594 May 15 01:33 flink-kubernetes-operator-1.0-SNAPSHOT-shaded.jar
-rw-r--r-- 1 flink flink  12911296 May 15 01:32 flink-kubernetes-shaded-1.0-SNAPSHOT.jar
-rw-r--r-- 1 flink flink     34682 May 15 01:33 flink-kubernetes-webhook-1.0-SNAPSHOT.jar
drwxr-xr-x 2 root  root       4096 May 15 01:37 licenses
```

### CODE REVIEW

**Comment by wangyang0918** [comment]
@gyfora @mbalassi  Would you like to have a look?

**Comment by wangyang0918** [comment]
It seems that the `collect_license_files.sh` could not work on arm64 env. I will have a look.

**Comment by mbalassi** [comment]
Thanks @wangyang0918! Will review this later today, at first glance big 👍 for modifying the working directory. 😏

**Review by mbalassi — APPROVED** [review]
LGTM, tested locally.

**Pull request merged**
