### PR TITLE
[FLINK-30527] Validate flinkVersion change for suspended jobs

### PR DESCRIPTION
**Pull request by gyfora**
## What is the purpose of the change

The PR adds validation for flinkVersion changes on SUSPENDED application. If the flinkVersion is changed for an application that was suspended with last-state upgrade mode (relying on the HA metadata) this may lead to state loss depending on the flink version.

This validation is necessary to avoid unintentional state loss. 

If the user wants to change the flink version in these cases, they first have to restart the job with the old version then perform the upgrade from that state or use a savepoint.

## Brief change log

  - *Added required validation & tests*
  
## Verifying this change

New validator unit tests added to check the version change scenarios.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changes to the `CustomResourceDescriptors`: no
  - Core observer or reconciler logic that is regularly executed: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by morhidi** [comment]
Thanks for the PR @gyfora. Regarding:
> If the user wants to change the flink version in these cases, they first have to restart the job with the old version then perform the upgrade from that state or use a savepoint.

We should advise the user to follow these instructions. The validate error could contain this IMO. WDYT?

**Comment by morhidi** [comment]
Slightly related: How do you feel @gyfora about adding instructions / a link to instructions for manual restore steps, etc that users are supposed to perform.

**Comment by gyfora** [comment]
@morhidi i think improving the error message is a good idea and I will do that, but I wouldn’t add detailed instructions / links. This is not common practice I feel and this also this is a manual recovery scenario but simply a spec validation error .

**Comment by morhidi** [comment]
> @morhidi i think improving the error message is a good idea and I will do that, but I wouldn’t add detailed instructions / links. This is not common practice I feel and this also isn’t a manual recovery scenario but simply a spec validation error .

But the instructions are so specific ` they first have to restart the job with the old version then perform the upgrade from that state or use a savepoint`. We should do something with it. The users should know how to address the validation error.

**Comment by gyfora** [comment]
The validation is about the version only, the user can restart the job with the old version but change the spec otherwise. This is not something we should do automatically for an already suspended job.

**Comment by gyfora** [comment]
Maybe I just don’t understand what your concrete suggestion is :)

**Comment by morhidi** [comment]
> Maybe I just don’t understand what your concrete suggestion is :)

Just append this to the validation error you already added: `they first have to restart the job with the old version then perform the upgrade from that state or use a savepoint.` Otherwise the users wont know what to do.

**Comment by gyfora** [comment]
Makes sense, I will do this tomorrow

**Pull request merged**
