### PR TITLE
[FLINK-26795] Fix the CI not fail fast after build failed

### PR DESCRIPTION
**Pull request by Aitozi**
Minor fix for the CI command

### CODE REVIEW

**Comment by wangyang0918** [comment]
@Aitozi Do you verify that the github action exits when `mvn install` failed?

**Comment by wangyang0918** [comment]
@Aitozi Do you verify that the github action exits when `mvn install` failed?

**Comment by Aitozi** [comment]
@wangyang0918 Yes, This pipeline verify it.

https://github.com/Aitozi/flink-kubernetes-operator/runs/5639643537?check_suite_focus=true

**Review by wangyang0918 — APPROVED** [review]
+1

**Review by mbalassi — APPROVED** [review]
Thanks, I run into this yesterday but did not fully understand what happened at the time. Happy that you caught it. Merging...

**Pull request merged**
