### PR TITLE
FLINK-32103 Update RBAC for OpenShift Deployment

### PR DESCRIPTION
**Pull request by jbusche**
## What is the purpose of the change

Noticing in the 1.5.0-rc1 and 1.5.0-rc2 that we're having a problem deploying on OpenShift.  The solution is to either manually update the flink-kubernetes-operator.v1.5.0 clusterrole, but a better way is to update the rbac.yaml.  In either case, a `- flinkdeployments/finalizers` is needed in the flink.apache.org apiGroup.

The following PR adds this finalizer for the deployment to succeed.

## Brief change log

  - *the `- flinkdeployments/finalizers` resource is added to the  flink.apache.org apiGroup*

## Verifying this change
This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): No
  - The public API, i.e., is any changes to the `CustomResourceDescriptors`: No
  - Core observer or reconciler logic that is regularly executed: No

## Documentation

  - Does this pull request introduce a new feature? No
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by jbusche** [comment]
Trying a new deployment on both a KIND cluster (non OpenShift) as well as two OpenShift clusters to verify the change.  Will post results here.

**Comment by jbusche** [comment]
OK - the KIND cluster looks good - still deploying the samples fine.
```
NAME                                                     READY   STATUS    RESTARTS   AGE
basic-example-5bbd68657d-4dgj5                           1/1     Running   0          3m44s
basic-example-taskmanager-1-1                            1/1     Running   0          3m14s
basic-session-deployment-only-example-57994c7d96-bmlr6   1/1     Running   0          3m19s
basic-session-deployment-only-example-taskmanager-1-1    1/1     Running   0          2m49s
basic-session-deployment-only-example-taskmanager-1-2    1/1     Running   0          2m49s
flink-kubernetes-operator-6b659d866-4t8g7                2/2     Running   0          4m26s
```
The flink clusterrole looks good:
```
oc describe clusterrole flink-operator |grep flinkdeployments
  flinkdeployments.flink.apache.org/finalizers  []                 []              [*]
  flinkdeployments.flink.apache.org/status      []                 []              [*]
  flinkdeployments.flink.apache.org             []                 []              [*]
```

**Comment by jbusche** [comment]
OpenShift 4.10.54 is looking good with the PR:
```
oc get pods,flinkdeployments -n default                                                                                      api.jim410.cp.fyre.ibm.com: Mon May 15 16:16:24 2023

NAME                                                         READY   STATUS    RESTARTS   AGE
pod/basic-example-5b547c9669-cj8pz                           1/1     Running   0          5m37s
pod/basic-example-taskmanager-1-1                            1/1     Running   0          5m8s
pod/basic-session-deployment-only-example-77957ff659-rvp5h   1/1     Running   0          3m23s
pod/basic-session-deployment-only-example-taskmanager-1-1    1/1     Running   0          2m39s
pod/basic-session-deployment-only-example-taskmanager-1-2    1/1     Running   0          2m39s
pod/flink-kubernetes-operator-66f8544889-sjjm5               2/2     Running   0          8m38s

NAME                                                                     JOB STATUS   LIFECYCLE STATE
flinkdeployment.flink.apache.org/basic-example                           RUNNING      STABLE
flinkdeployment.flink.apache.org/basic-session-deployment-only-example                STABLE
```
and the clusterrole looks good:
```
oc describe clusterrole flink-kubernetes-operator.v1.5.0-866bfd99dd  |grep flinkdeployments
  flinkdeployments.flink.apache.org/finalizers  []                 []              [*]
  flinkdeployments.flink.apache.org/status      []                 []              [*]
  flinkdeployments.flink.apache.org             []                 []              [*]

**Comment by jbusche** [comment]
OC 4.12.7 looks good too - I tried both in a single namespace as well as in the default `openshift-operators` where it can control all namespaces... looked good!

**Comment by mbalassi** [comment]
Thanks, @jbusche. Could you please also add `flinksessionjobs/finalizers` for the sake of completeness then?

**Comment by jbusche** [comment]
Sure @mbalassi, I'll re-test it again to make sure...

**Comment by jbusche** [comment]
Testing now, both with helm installs (OpenShift and regular Kubernetes) and OLM installs.  Will post results.

**Comment by jbusche** [comment]
Basic Kubernetes (on Kind) looks good
- clusterrole has the finalizers
- examples are deploying/running

**Comment by jbusche** [comment]
Looks good on OpenShift with OLM and also with the regular helm install:
```
oc get pods
NAME                                                              READY   STATUS      RESTARTS   AGE
55cc5ac1cd3d229c4038ac676a95c2cb7370452e2b8c810b8628d57501tr47c   0/1     Completed   0          5m7s
basic-example-7f7866dfdb-r5dbn                                    1/1     Running     0          2m52s
basic-example-taskmanager-1-1                                     1/1     Running     0          2m22s
basic-session-deployment-only-example-54fb75d764-vszc2            1/1     Running     0          2m50s
basic-session-deployment-only-example-taskmanager-1-1             1/1     Running     0          2m8s
basic-session-deployment-only-example-taskmanager-1-2             1/1     Running     0          2m8s
flink-kubernetes-operator-7877b7996-8wjvd                         2/2     Running     0          4m38s
olm-flink-operator-catalog-hnvlf                                  1/1     Running     0          5m42s
```
I feel it's good to merge, thanks!

**Pull request merged**
